server:
  port: 10001

spring:
  application:
    name: index12306-user${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.101.68
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.68:8848
        namespace: 5d564687-22f7-482b-941e-20b8ab3dbe9f
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: 192.168.101.68:8686
        port: 8719
      datasource:
        flow-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
            username: nacos
            password: nacos
        degrade-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
            username: nacos
            password: nacos
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

framework:
  fastjson:
    safe-mode: true
  cache:
    redis:
      value-timeout: 50000
      bloom-filter:
        user-register:
          name: user_register_cache_penetration_bloom_filter${unique-name:}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
