server:
  port: 10003

spring:
  application:
    name: index12306-order${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.68:8848
        namespace: 5d564687-22f7-482b-941e-20b8ab3dbe9f
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: 192.168.101.68:8686
        port: 8719
      datasource:
        flow-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
            username: nacos
            password: nacos
        degrade-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
            username: nacos
            password: nacos
        system-rules:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-system-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: system
            username: nacos
            password: nacos
  data:
    redis:
      host: 192.168.101.68
      port: 6379
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safe-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 192.168.101.68:9876
  producer:
    group: index12306_order${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
