server:
  port: 10000
spring:
  application:
    name: index12306-gateway${unique-name:}-service
  profiles:
    active: aggregation
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.68:8848
        ip: 192.168.101.1
        namespace: 5d564687-22f7-482b-941e-20b8ab3dbe9f
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
